In [1]:
import pandas as pd  
import warnings  
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd  
import warnings  

warnings.filterwarnings("ignore")
df3 = pd.read_excel('data/4sheet/3.xlsx', engine='openpyxl')
df4 = pd.read_excel('data/4sheet/4.xlsx', engine='openpyxl')
df4.columns = df3.columns  
data = pd.concat([df3, df4], axis=0)

In [3]:
import pandas as pd  

start_date = '2024-03-01'  
end_date = '2024-03-07'  
filtered_df = data[(data['下单时间'] >= start_date) & (data['下单时间'] <= end_date)]    
print('删除前数据条数', filtered_df.shape[0])

time_cols = [col for col in filtered_df.columns if '时间' in col]

for col in time_cols:
    filtered_df[col] = pd.to_datetime(filtered_df[col], errors='coerce')    
    filtered_df = filtered_df.dropna(subset=[col])  
filtered_df['下单时间'] = filtered_df['下单时间'].astype(str)
# 定义正则表达式模式，匹配并提取A和B
pattern = r'(\w+):(\w+)'
filtered_df[['小时', '分钟']] = filtered_df['下单时间'].str.extract(pattern)
filtered_df['小时'] = pd.to_numeric(filtered_df['小时'], errors='coerce')
filtered_df['分钟'] = pd.to_numeric(filtered_df['分钟'], errors='coerce')
filtered_df['分钟桶'] = filtered_df['小时'] * 60 + filtered_df['分钟']
filtered_df['日期'] = filtered_df['下单时间'].astype(str)
filtered_df['日期'] = filtered_df['日期'].apply(lambda x : x.split(" ")[0])

print('删除后数据条数', filtered_df.shape[0])

删除前数据条数 151542
删除后数据条数 149877

## 按城市保存数据

In [4]:
for city_id in set(filtered_df['城市']):
    data_clean_city = filtered_df[filtered_df['城市'] == city_id]
    data_clean_city.to_csv(f"./data/citylog/{city_id}_log.csv", index = False)

## 分桶保留最后一次派单时间的数据

In [7]:
import pandas as pd
df = filtered_df[['订单编号', '派单时间', '分配类型']] 
# 假设df是您的DataFrame
# 对数据按订单编号和派单类型分组，计算每个分组的最大最小时间以及计数
grouped = df.groupby(['订单编号', '分配类型']).agg(
    最大派单时间=('派单时间', 'max'),
    最小派单时间=('派单时间', 'min'),
    派单数量=('派单时间', 'count')
).reset_index()

# 对分组结果进行透视，以便将人工和机器派单分开到不同的列
pivot_df = grouped.pivot_table(index='订单编号', 
                               columns='分配类型', 
                               values=['最大派单时间', '最小派单时间', '派单数量'],
                               aggfunc='first').fillna(0)

pivot_df.columns = ['_'.join(col) for col in pivot_df.columns]
pivot_df.rename(columns={'最大派单时间_人工派单': '人工派单最大时间',
                         '最大派单时间_机器派单': '机器派单最大时间',
                         '最小派单时间_人工派单': '人工派单最小时间',
                         '最小派单时间_机器派单': '机器派单最小时间',
                         '派单数量_人工派单': '人工派单次数',
                         '派单数量_机器派单': '机器派单次数'}, inplace=True)
pivot_df.reset_index(inplace=True)

# # 计算每个订单的最大和最小派单时间（不区分人工或机器）
order_times = df.groupby('订单编号')['派单时间'].agg(最大派单时间='max', 最小派单时间='min').reset_index()

# # 合并订单的最大最小时间与派单类型的统计信息
final_df = pd.merge(order_times, pivot_df, on='订单编号', how='left')
final_df['最终类型'] = final_df.apply(lambda row: '人工' if row['最大派单时间_人工分配'] == row['最大派单时间'] else '机器', axis=1)

In [8]:
final_df[final_df['订单编号'] == 1764942758041120768]

,订单编号,最大派单时间,最小派单时间,最大派单时间_人工分配,最大派单时间_自动分配,最小派单时间_人工分配,最小派单时间_自动分配,派单数量_人工分配,派单数量_自动分配,最终类型
112711,1764942758041120768,2024-03-05 16:34:25,2024-03-05 16:16:40,2024-03-05 16:34:25,2024-03-05 16:16:40,2024-03-05 16:21:14,2024-03-05 16:16:40,4.0,1.0,人工

In [9]:
cols = ['订单编号','下单时间',	'开始调度时间', '骑手接单时间','骑手到店时间','骑手取餐时间','骑手到达时间','导航距离','小时','分钟','分钟桶']
filtered_df_unique= filtered_df[cols].drop_duplicates(subset=cols)
filtered_df_unique.head()

,订单编号,下单时间,开始调度时间,骑手接单时间,骑手到店时间,骑手取餐时间,骑手到达时间,导航距离,小时,分钟,分钟桶
19,1763248058112438272,2024-03-01 00:01:11,2024-03-01 00:02:00,2024-03-01 00:03:43,2024-03-01 00:09:47,2024-03-01 00:27:09,2024-03-01 00:27:58,105.0,0,1,1
20,1763247981091889152,2024-03-01 00:00:53,2024-03-01 00:03:00,2024-03-01 00:03:48,2024-03-01 00:06:40,2024-03-01 00:15:50,2024-03-01 00:18:34,2925.0,0,0,0
21,1763248312458682368,2024-03-01 00:02:12,2024-03-01 00:03:00,2024-03-01 00:03:35,2024-03-01 00:04:44,2024-03-01 00:17:53,2024-03-01 00:20:56,742.0,0,2,2
22,1763248461305982976,2024-03-01 00:02:47,2024-03-01 00:03:00,2024-03-01 00:03:37,2024-03-01 00:04:23,2024-03-01 00:19:29,2024-03-01 00:19:41,1051.0,0,2,2
23,1763248291571048448,2024-03-01 00:02:07,2024-03-01 00:03:00,2024-03-01 00:03:37,2024-03-01 00:05:02,2024-03-01 00:10:07,2024-03-01 00:18:28,3337.0,0,2,2

In [10]:
time_df = filtered_df_unique.merge(final_df)
time_df.head()

,订单编号,下单时间,开始调度时间,骑手接单时间,骑手到店时间,骑手取餐时间,骑手到达时间,导航距离,小时,分钟,分钟桶,最大派单时间,最小派单时间,最大派单时间_人工分配,最大派单时间_自动分配,最小派单时间_人工分配,最小派单时间_自动分配,派单数量_人工分配,派单数量_自动分配,最终类型
0,1763248058112438272,2024-03-01 00:01:11,2024-03-01 00:02:00,2024-03-01 00:03:43,2024-03-01 00:09:47,2024-03-01 00:27:09,2024-03-01 00:27:58,105.0,0,1,1,2024-03-01 00:03:30,2024-03-01 00:03:30,2024-03-01 00:03:30,0,2024-03-01 00:03:30,0,1.0,0.0,人工
1,1763247981091889152,2024-03-01 00:00:53,2024-03-01 00:03:00,2024-03-01 00:03:48,2024-03-01 00:06:40,2024-03-01 00:15:50,2024-03-01 00:18:34,2925.0,0,0,0,2024-03-01 00:03:30,2024-03-01 00:03:30,0,2024-03-01 00:03:30,0,2024-03-01 00:03:30,0.0,1.0,机器
2,1763248312458682368,2024-03-01 00:02:12,2024-03-01 00:03:00,2024-03-01 00:03:35,2024-03-01 00:04:44,2024-03-01 00:17:53,2024-03-01 00:20:56,742.0,0,2,2,2024-03-01 00:03:31,2024-03-01 00:03:31,0,2024-03-01 00:03:31,0,2024-03-01 00:03:31,0.0,1.0,机器
3,1763248461305982976,2024-03-01 00:02:47,2024-03-01 00:03:00,2024-03-01 00:03:37,2024-03-01 00:04:23,2024-03-01 00:19:29,2024-03-01 00:19:41,1051.0,0,2,2,2024-03-01 00:03:32,2024-03-01 00:03:32,0,2024-03-01 00:03:32,0,2024-03-01 00:03:32,0.0,1.0,机器
4,1763248291571048448,2024-03-01 00:02:07,2024-03-01 00:03:00,2024-03-01 00:03:37,2024-03-01 00:05:02,2024-03-01 00:10:07,2024-03-01 00:18:28,3337.0,0,2,2,2024-03-01 00:03:32,2024-03-01 00:03:32,0,2024-03-01 00:03:32,0,2024-03-01 00:03:32,0.0,1.0,机器

In [11]:
time_df[time_df['订单编号'] == 1764942758041120768].head()

,订单编号,下单时间,开始调度时间,骑手接单时间,骑手到店时间,骑手取餐时间,骑手到达时间,导航距离,小时,分钟,分钟桶,最大派单时间,最小派单时间,最大派单时间_人工分配,最大派单时间_自动分配,最小派单时间_人工分配,最小派单时间_自动分配,派单数量_人工分配,派单数量_自动分配,最终类型
112672,1764942758041120768,2024-03-05 16:15:19,2024-03-05 16:16:00,2024-03-05 16:34:48,2024-03-05 16:40:32,2024-03-05 16:41:00,2024-03-05 16:49:20,2571.0,16,15,975,2024-03-05 16:34:25,2024-03-05 16:16:40,2024-03-05 16:34:25,2024-03-05 16:16:40,2024-03-05 16:21:14,2024-03-05 16:16:40,4.0,1.0,人工

In [19]:
# 定义一个函数来移除列名中的特定字符串
def rename_columns(columns, ignore_strings):
    return [col.replace(s, '').strip() for s in ignore_strings for col in columns]

# 要忽略的字符串列表
ignore_strings = ["时间"]

# 重新命名列名
new_column_names = rename_columns(time_df.columns.tolist(), ignore_strings)
# 应用新的列名
time_df.columns = new_column_names

ignore_strings = ["骑手"]
new_column_names = rename_columns(time_df.columns.tolist(), ignore_strings)
# 应用新的列名
time_df.columns = new_column_names

In [20]:
time_df.head()

,订单编号,下单,开始调度,接单,到店,取餐,到达,导航距离,小时,分钟,分钟桶,最大派单,最小派单,最大派单_人工分配,最大派单_自动分配,最小派单_人工分配,最小派单_自动分配,派单数量_人工分配,派单数量_自动分配,最终类型
0,1763248058112438272,2024-03-01 00:01:11,2024-03-01 00:02:00,2024-03-01 00:03:43,2024-03-01 00:09:47,2024-03-01 00:27:09,2024-03-01 00:27:58,105.0,0,1,1,2024-03-01 00:03:30,2024-03-01 00:03:30,2024-03-01 00:03:30,0,2024-03-01 00:03:30,0,1.0,0.0,人工
1,1763247981091889152,2024-03-01 00:00:53,2024-03-01 00:03:00,2024-03-01 00:03:48,2024-03-01 00:06:40,2024-03-01 00:15:50,2024-03-01 00:18:34,2925.0,0,0,0,2024-03-01 00:03:30,2024-03-01 00:03:30,0,2024-03-01 00:03:30,0,2024-03-01 00:03:30,0.0,1.0,机器
2,1763248312458682368,2024-03-01 00:02:12,2024-03-01 00:03:00,2024-03-01 00:03:35,2024-03-01 00:04:44,2024-03-01 00:17:53,2024-03-01 00:20:56,742.0,0,2,2,2024-03-01 00:03:31,2024-03-01 00:03:31,0,2024-03-01 00:03:31,0,2024-03-01 00:03:31,0.0,1.0,机器
3,1763248461305982976,2024-03-01 00:02:47,2024-03-01 00:03:00,2024-03-01 00:03:37,2024-03-01 00:04:23,2024-03-01 00:19:29,2024-03-01 00:19:41,1051.0,0,2,2,2024-03-01 00:03:32,2024-03-01 00:03:32,0,2024-03-01 00:03:32,0,2024-03-01 00:03:32,0.0,1.0,机器
4,1763248291571048448,2024-03-01 00:02:07,2024-03-01 00:03:00,2024-03-01 00:03:37,2024-03-01 00:05:02,2024-03-01 00:10:07,2024-03-01 00:18:28,3337.0,0,2,2,2024-03-01 00:03:32,2024-03-01 00:03:32,0,2024-03-01 00:03:32,0,2024-03-01 00:03:32,0.0,1.0,机器

In [23]:
time_df[time_df['订单编号'] == 1764942758041120768].head()

,订单编号,下单,开始调度,接单,到店,取餐,到达,导航距离,小时,分钟,分钟桶,最大派单,最小派单,最大派单_人工分配,最大派单_自动分配,最小派单_人工分配,最小派单_自动分配,派单数量_人工分配,派单数量_自动分配,最终类型
112672,1764942758041120768,2024-03-05 16:15:19,2024-03-05 16:16:00,2024-03-05 16:34:48,2024-03-05 16:40:32,2024-03-05 16:41:00,2024-03-05 16:49:20,2571.0,16,15,975,2024-03-05 16:34:25,2024-03-05 16:16:40,2024-03-05 16:34:25,2024-03-05 16:16:40,2024-03-05 16:21:14,2024-03-05 16:16:40,4.0,1.0,人工